# Generated by Django 4.0.3 on 2022-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_models_model_file_alter_disease_disease_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
