# Generated by Django 4.0.3 on 2022-04-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_doctor_birthdate_alter_engineer_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='name',
            new_name='disease_name',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='name',
            new_name='model_name',
        ),
    ]
