# Generated by Django 4.0.3 on 2022-04-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_rename_name_disease_disease_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='accuracy',
        ),
    ]
