# Generated by Django 4.0.3 on 2022-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
