# Generated by Django 4.0.3 on 2022-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_alter_doctor_name_alter_engineer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.AlterField(
            model_name='models',
            name='model_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
