# Generated by Django 4.0.3 on 2022-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_images_alter_models_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='Files'),
        ),
    ]
