# Generated by Django 4.0.3 on 2022-06-18 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_delete_images_remove_dataset_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(auto_created=datetime.timezone),
        ),
    ]
