# Generated by Django 4.0.3 on 2022-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_alter_login_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
