# Generated by Django 4.0.3 on 2022-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0019_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioModels',
            fields=[
                ('biomodel_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('biomodel_name', models.CharField(max_length=250, unique=True)),
                ('biomodel_file', models.FileField(default='null', upload_to='BioFiles')),
            ],
        ),
    ]
